name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftLint
        run: brew install swiftlint || true
      - name: SwiftLint
        run: swiftlint lint --quiet || true
      - name: Build Swift package
        run: |
          cd ios-sdk
          swift build
      - name: Run Swift tests
        run: |
          cd ios-sdk
          swift test
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.2.1/ktlint && chmod a+x ktlint
      - name: ktlint
        run: ./ktlint "**/*.kt" "**/*.kts" || true
      - name: Build Android library
        run: |
          cd android-sdk
          ./gradlew :assembleDebug --no-daemon
      - name: Run Android unit tests
        run: |
          cd android-sdk
          ./gradlew :testDebugUnitTest --no-daemon
