name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build Swift package
        run: |
          cd ios-sdk
          swift build
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Build Android library
        run: |
          cd android-sdk
          ./gradlew :assembleDebug
